### ISSUE TITLE
Improve regexp unlikelyCandidates

### ISSUE THREAD

**Issue by PedroAmorim** [andreskrey/readability.php#36]
Hello Andres!

In some cases, we need to change the unlikelyCandidates regexp in order to remove the bad content.
Example:
http://mashable.com/2017/11/03/xbox-one-x-review/
Class "shopping-disclaimer" need to be removed.

In this case, I think to make a PR to add the word "disclaimer" to the regexp.

But, what do you think about using a configuration parameter to change the unlikelyCandidate regexp for  other cases more tricky?

I also need to add some logs to know why some nodes are not removed from content.
So I think it will be nice to have a logger like [Monolog](https://github.com/Seldaek/monolog) a simple debug mode.
I would like to have your opinion about that too.

Thanks!

PS: You reached an awesome milestone with this v1! 
Congrats! 👍

**Comment by andreskrey** [comment]
Hi!

So you have two requests:

- Modify the unlikelyCandidates regex: While I do like the idea of allowing the user to tweak the inner workings of the system, I think your solution is too focused on your specific needs. Today we allow the user to inject a custom unlikelyCandidates string, tomorrow another user wants to modify the divToPElements array, the day after... you get the point. What I'm thinking is allowing the user to inject middleware in some specific points of the execution. You'll need to create your own class (that must implement a middleware interface) and your functions would be called at specific points. This would allow you, instead of modifying the regex, to clean the nodes on your own and use whatever you like.

- Logging the process: I like this idea, specially as an optional thing to inject. Although I have my concerns about logging everything. The only things I would find useful to log is when [we drop flags and reparse the text](https://github.com/andreskrey/readability.php/blob/master/src/Readability.php#L152). Can you clarify what you would like to see in the logs and why?

I'll keep this open until we decide what to do and then I'll create new issues.

Thanks!

**Comment by PedroAmorim** [comment]
Hi!

> allowing the user to inject middleware in some specific points of the execution

I totally agree with you, is the best way to do that!

> Can you clarify what you would like to see in the logs and why?

I need to know for what reason a specific node has been(or not) cleared.

thanks!

**Comment by andreskrey** [comment]
Logging is already implemented in the [logging](https://github.com/andreskrey/readability.php/tree/logging) branch. Middleware... is going to take more time :/

**Comment by andreskrey** [comment]
Also, feel free to submit PRs to that branch if you want to add more specific logging

**Comment by PedroAmorim** [comment]
Thanks!

**Comment by PedroAmorim** [comment]
Would you mind to merge logging in master branch?

**Comment by andreskrey** [comment]
Yeah, the event manager is taking more time than I expected. I'll do the release tonight.

**Comment by PedroAmorim** [comment]
Ok, good luck! :)

**Comment by andreskrey** [comment]
Released: https://github.com/andreskrey/readability.php/releases/tag/v1.1.0

**Comment by andreskrey** [comment]
I hope you don't mind but I'm going to close this. After thinking about it I decided that the event manager approach is out of the scope of this project.

If you want to modify a certain part of the code because it's failing to parse a specific website, maybe instead of tweaking your own instance we should find a way to tweak the algorithm and make it more universal.

Feel free to submit a test case that fails and we can work together to figure out what's wrong with the current code.

**Comment by PedroAmorim** [comment]
Hi!

No problem, you are right, this project should follow initial Mozilla's project, so I agree with you.

By the way, if someone needs to overwrite the regexp (this is a totally subjective point, I think), it's now possible since v1.0.0 because $regexps is public.
So we could simply change the regexp like this:

```
use andreskrey\Readability\Nodes\NodeUtility;

NodeUtility::$regexps['unlikelyCandidates'] = '/banner|breadcrumbs|combx|comment|community|cover-wrap|disqus|extra|foot|header|legends|menu|related|remark|replies|rss|shoutbox|sidebar|skyscraper|social|sponsor|supplemental|ad-break|agegate|pagination|pager|popup|yom-remote';

$config = new Configuration;
$readability = new Readability($config);
```
Thanks!
