### ISSUE TITLE
Infinite loop on search of parentTopCandidate

### ISSUE THREAD

**Issue by PedroAmorim** [andreskrey/readability.php#42]
Hi!

I have another bug with parentTopCandidate's code when I try to parse:
[http://www.motomag.com/Honda-Goldwing-2018-Tambour-battant-ca-donne-quoi.html](http://www.motomag.com/Honda-Goldwing-2018-Tambour-battant-ca-donne-quoi.html)

```
Trying to get property of non-object in /vendor/andreskrey/readability.php/src/Readability.php on line 955
Trying to get property of non-object in /vendor/andreskrey/readability.php/src/Readability.php on line 964
```

I try to fix that by check if parentNode is null each time we call -`>parentNode`, but this seems more complicated than that, because parentOfTopCandidate it's needed for "DOMElement $sibling" which failed with `Call to a member function getChildren() on null`.

I hope this help.

**Comment by andreskrey** [comment]
For some reason we are reaching the DOMDocument node while scanning for ancestors, which of course doesn't have a parent node. JS version seems to parse the text correctly, I'll try to check what's the difference between our behavior and the JS version behavior.

**Comment by andreskrey** [comment]
Fixed. Just pushed a change to the master branch to avoid the infinite loop. Parsing is still incorrect because we are selecting a bunch of links as the main text. This happens because those links have the "modal" class and I (sorry!) [proposed the removal of that keyword](https://github.com/mozilla/readability/commit/01ffd0c6174151725655850ec04d452b303bfdf2) as an unlikely candidate.

We'll have to come up with a tweak to fix the parsing of that specific site, but at least the infinite loop will not happen anymore.

**Comment by PedroAmorim** [comment]
Thanks!
